### ISSUE TITLE
Haskelloids does not build with ghc 8.4.4 and 8.6.1

### ISSUE THREAD

**Issue by chriz-zeller** [keera-studios/Haskelloids#30]
[Build logs](https://travis-ci.org/keera-studios/Haskelloids/builds/442293001?utm_source=github_status&utm_medium=notification)

Reason:
```
Graphics/HGL/Internals/Events.hs:23:68: error:
    Module ‘Control.Concurrent.Chan’ does not export ‘isEmptyChan’
```
`isEmptyChan` is deprecated and is latest seen in [base-4.10.1.0](http://hackage.haskell.org/package/base-4.10.1.0/docs/Control-Concurrent-Chan.html) (compare with [base-4.11.0.0](http://hackage.haskell.org/package/base-4.11.0.0/docs/Control-Concurrent-Chan.html))

[GHC 8.4 uses base 4.11.0.0](https://wiki.haskell.org/Base_package)

**Comment by Vincibean** [comment]
@chriz-zeller I tinkered a bit with the dependencies in #32 and the problem seems to be fixed.
Let me know if something else is needed.

**Comment by myroslambda** [comment]
@Vincibean I will be merging this one. I'll try it and let you know. Thank you!
